# Generated by Django 6.0.4 on 2026-04-23 15:59

import filmy_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=2000)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('action', 'Akcja'), ('comedy', 'Komedia'), ('drama', 'Dramat'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('romance', 'Romans'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('animation', 'Animacja'), ('documentary', 'Dokumentalny'), ('crime', 'Kryminał'), ('mystery', 'Tajemnica'), ('adventure', 'Przygodowy'), ('family', 'Familijny'), ('war', 'Wojenny'), ('history', 'Historyczny'), ('music', 'Muzyczny'), ('sport', 'Sportowy'), ('western', 'Western'), ('biography', 'Biograficzny')], default='action', verbose_name=filmy_app.models.Film.Category)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
            },
        ),
    ]
