# Generated by Django 6.0.4 on 2026-04-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.CharField(choices=[('action', 'Akcja'), ('comedy', 'Komedia'), ('drama', 'Dramat'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('romance', 'Romans'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('animation', 'Animacja'), ('documentary', 'Dokumentalny'), ('crime', 'Kryminał'), ('mystery', 'Tajemnica'), ('adventure', 'Przygodowy'), ('family', 'Familijny'), ('war', 'Wojenny'), ('history', 'Historyczny'), ('music', 'Muzyczny'), ('sport', 'Sportowy'), ('western', 'Western'), ('biography', 'Biograficzny')], default='action', max_length=20, verbose_name='Kategoria'),
        ),
    ]
