# Generated by Django 6.0.4 on 2026-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy_app', '0002_alter_film_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='movies_photos'),
        ),
        migrations.AddField(
            model_name='film',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
    ]
